watchlist:
- name: Apple Inc.
  symbol: AAPL
- name: Microsoft Corp.
  symbol: MSFT
- name: Alphabet Inc.
  symbol: GOOGL
- name: Amazon.com Inc.
  symbol: AMZN
- name: Tesla Inc.
  symbol: TSLA
- name: NVIDIA Corp.
  symbol: NVDA
- name: Meta Platforms Inc.
  symbol: META
- name: Palantir Technologies Inc. Class A Common Stock
  symbol: PLTR
- name: CoreWeave, Inc. Class A Common Stock
  symbol: CRWV
